name: "Solomon Rubin"
blog_title: "Thoughts and Ramblings"
description: "I am currently a <b>Software Systems Engineer</b> at the <b>MITRE</b> Corporation  <br />
            actively continuing my education and learning both in and out of school. <br />
            Over the last eight years I have developed an extensive technical skillset <br/>
            focusing on <b>Full-Stack Development</b> and general <b>Software Engineering</b>. <br />
            I have particular intrest in <b>Linux</b> and <b>Open Source</b> Software development."

url: "https://serubin.net"
# URL for open-graph things which appear not
# to get along with https
og_url: "http://serubin.net"

paginate: 6
paginate_path: "/blog/page/:num"
permalink: "/blog/:year/:month/:day/:title.html"

redirect_to_https: yes

highligher: pygments

plugins: 
    - jekyll-paginate
