name: "Solomon Rubin"
blog_title: "Thoughts, Talks, & More"

description: "I'm a <b>Software and Cyber Security Engineer</b> out of Washington DC who<br />
              is dedicated to continuously developing my technical and professional <br />
              skills through intensive <b>hands-on learning</b>. I have a particular focus in <br />
              the intersection of Cyber Security and Software Engineering as well as <br />
              significant experience within <b>System Architecture</b>. "

url: "https://serubin.net"
# URL for open-graph things which appear not
# to get along with https
og_url: "http://serubin.net"
redirect_to_https: yes


# Blog
paginate: 6
paginate_path: "/blog/page/:num"
permalink: "/blog/:year-:month-:day/:title"
future: true


highligher: pygments

plugins:
    - jekyll-paginate
