# vim: ts=2:sts=2:sw=2:expandtab

version: '3.7'

services:
  seafile:
    image: serubin/serubin-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.domain=serubin.net"
      - "traefik.frontend.rule=Host: serubin.net"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
